### PR TITLE
We were trying to intercept standard error when the user submits an empt...

### PR DESCRIPTION
**Pull request by nastysloper**
Brett Sanders (@brettsanders) and I attempted to address ticket #54 where a user's file must pass tests before being accepted. We were able to run the test but we were not able to gracefully intercept the error. We think this is because bob_test.rb waits for user input. Any advice would be appreciated so we can figure out how to proceed. Thanks!

screen shot 2013-08-04 at 5 01 13 pm

Fix #54

### CODE REVIEW

**Comment by kytrinyx** [comment]
Oooh. I forgot about Bob and his user input. On the one hand, it shouldn't be waiting for user input if they've finished the test suite, but that's a good point.

I'm in unknown territory, so just thinking out loud. Could we start the subprocess and keep a link to the pid, and then use that to kill the process if something takes too long?

I'd be totally OK with a hack that doesn't check bob if that lets you get something mostly working.

**Comment by kytrinyx** [comment]
Have you tried redefining `gets` so that it doesn't do anything? That might be difficult to do depending on how you're running the tests, but it could be worth a shot.

**Comment by nastysloper** [comment]
Hi Katrina,

We haven't taken another stab at it yet, but we want to get back to it.
Brett Sanders is up to his armpits with coursework at Dev Bootcamp, so it
will probably be a couple of weeks before we dive in again. But we are
really jazzed to take another crack at it. Super fun. And thanks for the
feedback! We will certainly try to implement those suggestions.

~Rich

**Comment by kytrinyx** [comment]
Very cool, and no hurry!

**Comment by kytrinyx** [comment]
Someone else got this working. I'm working with them to make sure that it's possible to submit without running the tests in case there are some platform-dependent weirdnesses.

I'm going to close the pull request. Thanks so much to both of you for working on this!

**Comment by nastysloper** [comment]
Super! I've got to get better so I can start chipping in. I'm missing out on the fun!

**Pull request closed without merging**
