### PR TITLE
Run test suites before submission

### PR DESCRIPTION
**Pull request by ecmendenhall**
Here's a first hack at fixing issue #54. 
### What's new:
- A `TestSuite` class that runs a submission's tests and captures stdout, stderr, and the exit code. This uses Open3 from the standard library. Initialize a `TestSuite` with an assignment's filename, then call `TestSuite.run` or `TestSuite.passes?` to run tests. `TestSuite` runs the test commands specified in the Exercism.io setup instructions for each language, and should print a friendly help message when the environment is misconfigured. `TestSuite` expects passing suites to exit 0 and considers everything else a failure.
- A new "test" command from the CLI. Run `exercism test <submission>` to run a submission's test suite.
### What's changed:
- I added passing and failing test fixtures for each current curriculum language. (Let me know if you think of a better way to test this). These require your environment to be set up according to the Exercism.io setup instructions for each language. Since they'll fail the Travis build, I extracted them to a separate Rake task. Run `rake test` to run default tests (including most of the `TestSuite` tests) and `rake test env_dependent` to add in the non-Ruby fixtures.
- The CLI runs tests as part of `exercism submit` and bounces failing submissions.
### What needs to change:
- The Haskell and Clojure tests from Exercism.io don't always exit correctly. I've added logic to the .hs and .clj test fixtures that handle exiting correctly on failure. Clojure tests are a simple fix—just wrap `(run-tests)` in a conditional:

```
(when (not (successful? (run-tests)))
  (System/exit 1))
```

Haskell tests are more complicated. I came up with something, but I'm a Haskell noob:

```
import Test.HUnit (Assertion, (@=?), runTestTT, Test(..), Counts (failures, errors))
import Control.Monad (void)
import System.Exit (ExitCode (ExitSuccess, ExitFailure), exitWith)
import FailingSubmission ( thisIsFalse )

[ ... ]

testsPass :: Counts -> Bool
testsPass testcounts = and [failures testcounts == 0,
                            errors   testcounts == 0]

exitStatus :: Counts -> ExitCode
exitStatus testcounts
  | testsPass testcounts = ExitSuccess
  | otherwise            = ExitFailure 1

main :: IO ()
main = do
  result <- runTestTT (TestList failingSubmissionTests)
  exitWith (exitStatus result)
```

If the Haskellers around here have a better solution, please feel free to add it. Point is, existing Haskell and Clojure assignments need to include these checks before an update to the gem goes live.
- Likewise, test suites for future languages and examples (Go, Rust, etc.) need to exit correctly.
- Since `TestSuite` runs the exact commands from the Exercism.io setup pages, it should be clear that these are hard requirements. For Clojure, this means Leiningen and the lein-exec plugin are now required. The other languages should be fine.

### CODE REVIEW

**Comment by ecmendenhall** [comment]
...and it looks like this is failing all the Travis jobs.

**Comment by ecmendenhall** [comment]
All fixed!

**Comment by kytrinyx** [comment]
Very cool! One question -- does `open3` work on Windows?

**Comment by kytrinyx** [comment]
It might be worth adding a flag to skip running the tests so that if running the tests via the gem doesn't work on the local system for some reason, then they can still use exercism.

**Comment by ecmendenhall** [comment]
I was thinking about a flag, too. I was on the fence, but it's a good idea. I'll ask around about open3—I have no idea whether it works on Windows. If not, it shouldn't be hard to extend the `TestRunner` class.

**Comment by Gaelan** [comment]
I wonder if it is possible to make sure that the test file meets these conditions:
1. It is the latest version from exercism.io, and has not been changed from that.
2. All skips have been removed.

**Comment by kytrinyx** [comment]
I'm actually not terribly worried about (1) -- people will sometimes have outdated test files, it doesn't seem like a big deal.

If they submit with skips, I'm guessing that they didn't know to remove them. That's usually pretty apparent when they submit (3 lines of code instead of, say 12 or 15). In that case I'd prefer it if a human helped explain to them.

If either of these become a big problem, I think it would make sense to rethink it, but as it stands I'm not worried about them.

**Comment by Gaelan** [comment]
Oh, also it would be nice to have the “you can’t submit until tests pass” message be a confirmation (“Tests aren’t passing. Really submit?”) instead of a hard “no”. When I’m really stumped, it’s nice to submit as far as you got with a comment asking for pointers. I’m not sure if this is allowed or not.

**Comment by kytrinyx** [comment]
Totally allowed. I think that would be a good idea ("really submit?" rather than a hard no, I mean).

**Comment by Gaelan** [comment]
Found a problem: the solutions are often named differently from the exercise names (the solution to `nucleotide-count` is `dna.rb`), but this assumes that the test and solution are named the same way. BTW I'm starting to use this as my `exercism` script, so I'll tell you anything I find.

**Comment by Gaelan** [comment]
It still doesn't work after I `cp dna.rb nucleotide-count.rb`:

```
Gaelan@gbs ~/D/C/E/r/nucleotide-count> exercism s nucleotide-count.rb 
Running test suite nucleotide-count_test.rb...

Run options: --seed 39411

# Running tests:

............

Finished tests in 0.001410s, 8510.6383 tests/s, 8510.6383 assertions/s.

12 tests, 12 assertions, 0 failures, 0 errors, 0 skips

You can't submit this assignment until the tests pass.
```

**Comment by ecmendenhall** [comment]
Thanks for all the feedback. I'll try and push some revisions this weekend. 

@Gaelan—does the test script exit 0 when you run it on its own? Let me know if you can reproduce this and I'll make sure there's a test case around it.

**Comment by Gaelan** [comment]
@ecmendenhall Yes.

**Comment by etrepum** [comment]
I've got a branch that fixes the test suites for all of the Haskell exercises to return an exit code of 1 if anything fails. I also wrote a script that verifies that the tests pass without error given the example.hs, I'm gonna try and see if I can get travis to CI that and then I'll submit a PR.

**Comment by kytrinyx** [comment]
I just realised that this pull request is still open, and nothing has been done or said about it in a very long time.

Since this gem is deprecated I'm going to close the pull request. Thanks, everyone, for the discussion.

**Pull request closed without merging**
