### PR TITLE
Adding CLI functionality to stash submissions for later use

### PR DESCRIPTION
**Pull request by kevinleugers**
Companion to exercism.io issue [#329](https://github.com/kytrinyx/exercism.io/issues/329)

### CODE REVIEW

**Comment by kytrinyx** [comment]
I think it would be easier to understand if this were `exercism stash save path/to/file` and `exercism stash pop` to match the language we use around stashing with git. Thoughts?

**Comment by Trevoke** [comment]
That is a tough call. On the one hand, I like not having to relearn an interface. On the other hand, what exactly makes sense here? I guess we can stash one submission per trail, but it seems like the most symmetrical behavior with respect to `exercism fetch` might be to do `exercism stash` and stash the current status of all the trails, and then `exercism stash pop` to retrieve the current status of all trails ?

**Comment by kytrinyx** [comment]
`exercism stash` is equivalent to to `exercism submit`, not `exercism fetch`. You can submit from anywhere on the file system, there's no reason to assume that you're standing in some logical file tree that includes the other current assignments that you're working on.

My biggest gripe is with the term `loot`. It seems completely arbitrary.

**Comment by Trevoke** [comment]
Well, if you're a pirate, you put stuff in the stash and loot it back out. It'd be great if the rest of the app used the same language.

Unfortunately, it doesn't, so `loot` is not a great choice.

`exercism stash` could behave much like `submit` and work from anywhere on the file system, but I gather this is not the issue we're discussing, and the matter of whether we're storing one submission or all of them has already been decided.

In that case, I'm guessing we may want to use `exercism retrieve bob.rb`.

**Comment by kytrinyx** [comment]
> Well, if you're a pirate, you put stuff in the stash and loot it back out.

Ah, thanks. I'm not very knowledgable about pirates.

**Comment by kevinleugers** [comment]
> Ah, thanks. I'm not very knowledgable about pirates.

Ah! I wasn't crazy about the naming either but it made sense to me. I should remember to go with the more logical choice that others will understand(ex. git conventions) :)

`exercism stash save /path/to/file` and `exercism stash pop` should work with how I'm updating the exercism.io side of things.

**Comment by sgerrand** [comment]
> Well, if you're a pirate, you put stuff in the stash and loot it back out.

Unfortunately `loot` is an overloaded term: it could equally refer to the contents of the `stash`. :older_man:

**Comment by kytrinyx** [comment]
I've lost track of the status on this. I think that the API side of things on kytrinyx/exercism.io has been merged. Is this pull request still valid?

**Comment by kevinleugers** [comment]
Still needed yes, but I need to finish testing a couple changes. I should have another commit tomorrow with the new command verbiage.

**Comment by kytrinyx** [comment]
Cool!

**Comment by kevinleugers** [comment]
Please review, I think this should be good to merge. I changed the CLI verbiage to be more in line with `git stash`. To save your in-progress stash file: `exercism stash save FILE`, then to download a stashed file: `exercism stash apply FILE`. 

Also added `exercism stash list` to view a list of your stashed submissions.

**Comment by kytrinyx** [comment]
Sweet, thank you!

**Pull request merged**
